### ISSUE TITLE
Kana is not centered on mobile

### ISSUE THREAD

**Issue by Krossmaskinen** [c-bandy/type-kana#224] opened 2021-04-08 11:24 UTC
On Android, Chrome and Firefox, the kana on top is offset to the right, making it impossible to see the whole text. Not possible to scroll or zoom either.

I'd be happy to contribute a fix tonight or tomorrow (Swedish time) ✌️

![Screenshot_20210408-132157](https://user-images.githubusercontent.com/1162364/114018372-72cfa480-986d-11eb-8860-b2d9fc791264.jpg)

**Comment by c-bandy** [comment] 2021-04-19 17:28
The current item is always centered so that you can see the previous items, this is by design. 

I think the bigger issue here is that the text is way too big on mobile. Feel free to submit a PR to scale it down a bit on smaller screens 👍

**Comment by c-bandy** [comment] 2021-04-19 17:28
Relates to #54

**Comment by Krossmaskinen** [comment] 2021-04-19 20:45
I see! I seem to have misunderstood how the app works. I thought you were supposed to fill in all of the visible kanas and submit, not just the first one.

**Comment by c-bandy** [comment] 2021-04-19 21:08
The behavior is perhaps a bit more easy to understand on the browser where you can see the whole thing

**Comment by c-bandy** [comment] 2021-05-01 18:15
I'm closing this in favor of #54

**Closed by c-bandy** 2021-05-01 18:15 UTC
Labels: enhancement
